/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface DrizzleDrizzleMigrations {
  created_at: Int8 | null;
  hash: string;
  id: Generated<number>;
}

export interface Users {
  address: string | null;
  created_at: Generated<Timestamp>;
  credit_card_cvv: string | null;
  credit_card_expiry: string | null;
  credit_card_number: string | null;
  email: string;
  email_code: string | null;
  email_verified_at: Timestamp | null;
  firstname: string | null;
  id: Generated<string>;
  lastname: string | null;
  phone: string | null;
  phone_code: string | null;
}

export interface DB {
  'drizzle.__drizzle_migrations': DrizzleDrizzleMigrations;
  users: Users;
}
